import time as t

# Problem 2 - Even Fibonacci Numbers
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

start = t.time()
def even_fib():
	heu = 0
	f = [0,1]
	evens = []
	lim = 4000000
	while (heu < lim):
		f = f[-2:]
		heu = sum(f)
		f.append(heu)
		if heu % 2 == 0 and heu < lim:
			evens.append(heu)
	return sum(evens)
print(even_fib())
print(t.time() - start)
