
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

fib = [1, 2, 3, 5]
carry = 0


while True:
    carry = fib[-1] + fib[-2]
    if carry < 4000000:
        fib.append(carry)
    else:
        break
    

sum_fib_even = 0

for term in fib:
    if term % 2 == 0:
        sum_fib_even += term

print(sum_fib_even)
